import Refractor from 'react-refractor';
import bash from 'refractor/lang/bash';
import csharp from 'refractor/lang/csharp';
import css from 'refractor/lang/css';
import go from 'refractor/lang/go';
import java from 'refractor/lang/java';
import javascript from 'refractor/lang/javascript';
import json from 'refractor/lang/json';
import jsx from 'refractor/lang/jsx';
import markdown from 'refractor/lang/markdown';
import php from 'refractor/lang/php';
import python from 'refractor/lang/python';
import ruby from 'refractor/lang/ruby';
import sass from 'refractor/lang/sass';
import scss from 'refractor/lang/scss';
import sql from 'refractor/lang/sql';
import tsx from 'refractor/lang/tsx';
import typescript from 'refractor/lang/typescript';
import xmlDoc from 'refractor/lang/xml-doc';
import yaml from 'refractor/lang/yaml';
import http from 'refractor/lang/http';
import latex from 'refractor/lang/latex';
import powershell from 'refractor/lang/powershell';

Refractor.registerLanguage(csharp);
Refractor.registerLanguage(css);
Refractor.registerLanguage(go);
Refractor.registerLanguage(java);
Refractor.registerLanguage(javascript);
Refractor.registerLanguage(json);
Refractor.registerLanguage(jsx);
Refractor.registerLanguage(markdown);
Refractor.registerLanguage(sql);
Refractor.registerLanguage(php);
Refractor.registerLanguage(python);
Refractor.registerLanguage(ruby);
Refractor.registerLanguage(sass);
Refractor.registerLanguage(scss);
Refractor.registerLanguage(bash);
Refractor.registerLanguage(tsx);
Refractor.registerLanguage(typescript);
Refractor.registerLanguage(xmlDoc);
Refractor.registerLanguage(yaml);
Refractor.registerLanguage(http);
Refractor.registerLanguage(latex);
Refractor.registerLanguage(powershell);